# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb48e6e266240af5601deb693fc23c83403ff7bd3d18f03e2ffe9dd8879a24710f84844b60be43316dbd7ac169b19853f52ef7bdab8fdbfc2b6df491c40c6bd

test:
  secret_key_base: 44c78fcbdb0e3f37ad84be34dc8d6e397dca23c77197c39aa44a4b6b8ee952880f0c44e4e652aef1106e19d1c63893090d72f094e0737f120bb99bac3ba68826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
